# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

from setuptools import find_packages, setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='fastapi-code-generator',
    version='0.0.1',
    python_requires='==3.*,>=3.7.0',
    project_urls={
        "homepage": "https://github.com/koxudaxi/fastapi-code-generator",
        "repository": "https://github.com/koxudaxi/fastapi-code-generator"
    },
    author='Koudai Aono',
    author_email='koxudaxi@gmail.com',
    license='MIT',
    classifiers=[
        'Development Status :: 2 - Pre-Alpha', 'Natural Language :: English',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: Implementation :: CPython'
    ],
    entry_points={
        "console_scripts": [
            "fastapi-codegen = fastapi_code_generator.__main__:app"
        ]
    },
    packages=find_packages(),
    package_dir={"": "."},
    package_data={"fastapi_code_generator": ["template/*.jinja2"]},
    install_requires=[],
    extras_require={
        "dev": [
            "black==19.10b0", "freezegun==1.*,>=1.1.0", "isort==4.3.21", "mypy",
            "pytest==6.*,>=6.2.0", "pytest-cov", "pytest-mock"
        ]
    },
)
